{
 "title": "Room Temperatures",
 "description": "Compare interior temperature with outside temperatures",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperaturen",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "UG - Vorplatz",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "UG - Waschküche",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EG - Küche",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EG - WC",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EG - Wohnen",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Bad",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jasmin",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jerome",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Elternbad",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Elternzimmer",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Vorplatz",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "OG - Zimmer Nord",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "query": "SELECT mean(\"temperatureAir\") FROM \"innoxel_weather_station\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Übersicht Heizventile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "Stellventil Ein / Aus" }
   ],
   "targets": [
    {
     "alias": "UG-Vorplatz-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "UG - Vorplatz",
     "query": "SELECT mean(\"heater_status\") FROM \"UG - Vorplatz\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "UG-Waschküche-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "UG - Waschküche",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+3" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "EG-Küche-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "EG - Küche",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+5" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "EG-WC-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "EG - WC",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+7" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "EG-Wohnen-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "EG - Wohnen",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+9" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Büro Jasmin-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jasmin",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+11" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Büro Jerome-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jerome",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+13" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Elternbad-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Elternbad",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+15" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Elternzimmer-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Elternzimmer",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+17" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Elternzimmer-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Elternzimmer",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+19" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Vorplatz-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Vorplatz",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+21" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "OG-Zimmer Nord-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "OG - Zimmer Nord",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+23" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UG - Vorplatz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UG-Vorplatz-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UG - Vorplatz",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "UG-Vorplatz-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UG - Vorplatz",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "UG - Waschküche",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UG - Waschküche Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UG - Waschküche",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "UG - Waschküche Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UG - Waschküche",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "EG - Wohnen",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EG-Wohnen-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - Wohnen",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "EG-Wohnen-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - Wohnen",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "EG - Küche",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EG-Küche-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - Küche",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "EG-Küche-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - Wohnen",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "EG - WC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "EG-WC-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - WC",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "EG-WC-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "EG - WC",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Bad",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Bad-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Bad",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Bad-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Bad",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Büro Jasmin",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Büro Jasmin-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jasmin",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Büro Jasmin-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jasmin",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Büro Jerome",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Büro Jerome-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jerome",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Büro Jerome-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Büro Jerome",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Elternbad",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Elternbad-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Elternbad",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Elternbad-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Elternbad",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Elternzimmer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Elternzimmer-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Elternzimmer",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Elternzimmer-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Elternzimmer",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Vorplatz",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Vorplatz-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Vorplatz",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Vorplatz-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Vorplatz",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  },
  {
   "title": "OG-Zimmer Nord",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "OG-Zimmer Nord-Temperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Zimmer Nord",
     "select": [
      [
       { "params": [ "roomTemperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "OG-Zimmer Nord-Heizung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OG - Zimmer Nord",
     "select": [
      [
       { "params": [ "heater_status" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    },
    {
     "alias": "Aussentemperatur",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "innoxel_weather_station",
     "select": [
      [
       { "params": [ "temperatureAir" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Region", "operator": "=", "value": "Neuendorf" }
     ]
    }
   ]
  }
 ]
}